### ISSUE TITLE
Enhancement is too slow to run.Is there any way to make them fast.Thanks in advance

### ISSUE THREAD

**Issue by nivetha-123** [tuvovan/MIRNet---Keras#11]

**Comment by tuvovan** [comment]
speed depends on lots of points. would you specify your machine you are using, the image size, etc..?

**Comment by nivetha-123** [comment]
if i give the input image size as mine ,i got a dimension error so that i convert all the image size to 100*100 .is that possible to run without particular image size.And i'm using Ubuntu

**Comment by tuvovan** [comment]
lets show your error message!

**Comment by nivetha-123** [comment]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,1838,362,128] vs. [1,1839,362,128]
	 [[{{node add_12/add_1}}]].Well i'm running test_delight code.Please give some solution for this it was running more than two days because of many images

**Comment by tuvovan** [comment]
seems like your images have the odd shape?? try to make it as multiplication of 2!
