### ISSUE TITLE
Several typos in MIRNet implementation

### ISSUE THREAD

**Issue by wonwoolee** [tuvovan/MIRNet---Keras#6]
Hi, 
I found some typos in `model.py`.  Would you please fix it ?

Line 82: Looks like `X ` should be `upper_branch` ?: 
https://github.com/tuvovan/MIRNet---Keras/blob/91c67be5c3bae331973cc3f754a36efe24c061bb/model.py#L79-L82

The same at Line 97: 
https://github.com/tuvovan/MIRNet---Keras/blob/91c67be5c3bae331973cc3f754a36efe24c061bb/model.py#L94-L97

Line 130: the second argument `level3_DAU_2 `should be `level2_DAU_2`:
https://github.com/tuvovan/MIRNet---Keras/blob/91c67be5c3bae331973cc3f754a36efe24c061bb/model.py#L130

**Comment by tuvovan** [comment]
hi, thank you for your contribution. lets make a pull request though! :D

**Comment by wonwoolee** [comment]
Sure I'll make one. :-)
