### ISSUE TITLE
ValueError: a weight file containing 446 layers into a model with 638 layers.

### ISSUE THREAD

**Issue by drbetulay-hub** [tuvovan/MIRNet---Keras#8]
Hi I attempt to run test_denoise.py, I got value error:  "You are trying to load a weight file containing 446 layers into a model with 638 layers". Thank you for your help.

**Comment by tuvovan** [comment]
Hi, thanks for your concern. 

I just found the the weight files were deprecated. Please feel free to clone the code and retrain the model.

Best,!

**Comment by ai-Ilike** [comment]
Is so bad!!!
